Portfolio Responsive Desktop Version
rehanullah748/Responsive-Portfolio-Version pull request #1
Opened 2022-09-03 15:11 UTC by rehanullah748

In this milestone
1. My Portfolio
2. Media query Used
3. Created in html and CSS

2022-09-03 17:13 UTC, franclobo requested changes
Hi @rehanullah748, 

Good job so far!
You are doing it well 👍🏽 there are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

- We could use descriptive name classes to make it easier to review. In programming, we spend more time reading our code than writing it.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-03 17:13 UTC, franclobo commented on README.md
> +
- [ ] Please 🙏🏽 erase the instruction from the README template and replace it with your own information to have a professional README file.

2022-09-03 17:13 UTC, franclobo commented on README.md
> +### Deployment
- [ ] For a professional README file, please 🙏🏽  we could erase those sections from the README template that we are not using yet.

2022-09-03 17:13 UTC, franclobo commented on README.md
> +👤 **Author1**
- [ ] Kindly add your name here to personalize your file. 👍🏽

2022-09-03 17:13 UTC, franclobo commented on README.md
> +👤 **Author2**
- [ ] Kindly we can replace the information on the README template with our information, you could add the name of your partner here to have a professional README file. 👆🏽

2022-09-03 17:13 UTC, franclobo commented on style.css
> +@media only screen and (min-width: 768px) {
- [ ] Please 🙏🏽 make sure that the mobile version still working as expected for a better user experience. (I couldn't see the rest of the branches in your repository.) In the desktop version, I can't see the home page. 👀 

https://user-images.githubusercontent.com/58642949/188279783-fd5816ba-0aae-4774-be1f-506b94d27110.mp4

2022-09-03 17:13 UTC, franclobo commented on style.css
> +  }
- [ ] Kindly correct the width of the screen to avoid horizontal scrolling for a better user experience. 👇🏽 

https://user-images.githubusercontent.com/58642949/188279932-ac2991fa-02d9-4fab-88d8-1a0d29e63f60.mp4

2022-09-03 17:13 UTC, franclobo commented on style.css
> +
- [ ] Please 🙏🏽 correct the styles of the buttons to be similar to the firma template.
- Your design
![image](https://user-images.githubusercontent.com/58642949/188280068-e167bccc-f106-41a2-b3fe-168f18b27dba.png)

![image](https://user-images.githubusercontent.com/58642949/188280193-4e5656b5-0479-4b14-bf3d-13ce701ee2ef.png)

![image](https://user-images.githubusercontent.com/58642949/188280233-f7f421f9-a343-4cec-ac71-ac117ce38425.png)

- Figma template
![image](https://user-images.githubusercontent.com/58642949/188280092-77e60fec-6429-442a-9ae6-72d445fadb46.png)

![image](https://user-images.githubusercontent.com/58642949/188280212-fb5fea13-3ac5-4735-a417-c44bae834fca.png)

![image](https://user-images.githubusercontent.com/58642949/188280241-76b91675-7084-4599-8b59-a8fd64923585.png)

![image](https://user-images.githubusercontent.com/58642949/188280253-d3637726-e9ec-4904-9b24-6f9515a00691.png)

2022-09-03 17:13 UTC, franclobo commented on style.css
> +
- [ ] Kindly check the words out in your design to be the same as the Figma template. Correct: "LET'S CONNECT", the button in the Figma template is "Get My Resume"

- [ ] Kindly add a grey background in the languages to be similar to the Figma template.

- Your design
![image](https://user-images.githubusercontent.com/58642949/188280540-38129536-22d2-4f94-9bee-83af1fe7af9b.png)

- Figma template
![image](https://user-images.githubusercontent.com/58642949/188280568-d127c2b9-648d-4384-bdee-53b5ec4b311f.png)

2022-09-03 17:13 UTC, franclobo commented on index.html
> +      </ul>
- [ ] Please 🙏🏽 review the path of the social media icons to see them in the browser, to have a better user experience.
![image](https://user-images.githubusercontent.com/58642949/188280697-b243a6ea-b479-4672-87f0-c50ab639756d.png)

2022-09-03 17:13 UTC, franclobo commented on style.css
> +  }
- [ ] Kindly correc t the button style to be similar to the figma template.
- Your design
![image](https://user-images.githubusercontent.com/58642949/188280779-27567730-c1a4-4383-b91a-e6dc154cd3db.png)

- Figma template
![image](https://user-images.githubusercontent.com/58642949/188280796-a7bef5d1-c449-4b3d-bf3d-28313530be89.png)

2022-09-03 17:13 UTC, franclobo commented on style.css
> +  }
- [ ] Please 🙏🏽 correct the button interaction to be similar to the Figma template.
- Your design 


https://user-images.githubusercontent.com/58642949/188280963-9345fd5e-9521-43a5-b073-df7877b41ec8.mp4


- Figma template
![image](https://user-images.githubusercontent.com/58642949/188280940-59782c7c-d2b8-42f5-b78b-6e2ef26fa4c9.png)

2022-09-03 19:28 UTC, Ismailco requested changes
### Hi @rehanullah748, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-03 19:28 UTC, Ismailco commented on README.md
> +
- [ ] As the previous reviewer suggested kindly make sure to change this section, and instead add some instruction on how to clone the repo or how to use your project
e.g
```
clone this repo
$ git clone repo_url.git
cd into the folder
$ cd name_of_the_project
````

2022-09-03 19:28 UTC, Ismailco commented on index.html
> +<body>
- [ ] As the previous reviewer mentioned kindly make sure the mobile version is still working fine and looks like Figma design, as for now it's not styled properly, this will make your design mobile responsive

|Your design|Figma design|
|-|-|
|![Screenshot_20220903_201113](https://user-images.githubusercontent.com/25227022/188284867-ccc85d7c-8559-49a5-8227-fdf3ad867ffc.png)|![Screenshot_20220903_201538](https://user-images.githubusercontent.com/25227022/188284974-757ec1e7-8a6f-4a7e-994b-5b17bfb16c32.png)|
|![Screenshot_20220903_201133](https://user-images.githubusercontent.com/25227022/188284872-ae179096-be32-433d-bad3-3b12d8cfc88e.png)|![Screenshot_20220903_201555](https://user-images.githubusercontent.com/25227022/188284989-dc0a16c6-3933-420a-9b97-21f38407abef.png)|
|![Screenshot_20220903_201146](https://user-images.githubusercontent.com/25227022/188284875-89449c62-6cc3-4c77-92db-b7318cf89586.png)|![Screenshot_20220903_201609](https://user-images.githubusercontent.com/25227022/188284998-77cdbb2a-8807-4161-b437-77bb5b14b197.png)|

2022-09-03 19:28 UTC, Ismailco commented on index.html
> +      </button>>
- [ ] As the previous reviewer suggested kindly consider using the same styles for buttons as the ones in the Figma design also make sure to implement styling for hover, and active status, this will make your website interactive

![Screenshot_20220901_215546](https://user-images.githubusercontent.com/25227022/188285064-1122c35a-4561-4e59-b770-d6663142b847.png)

2022-09-03 19:28 UTC, Ismailco commented on index.html
> +      </ul>
- [ ] As the previous reviewer suggested Kindly add a grey background in the languages so your design can be similar to the Figma one

|Your design|Figma design|
|-|-|
|![Screenshot_20220903_202029](https://user-images.githubusercontent.com/25227022/188285135-63be1fa5-9ad2-49d3-af0c-1d73465b0088.png)|![Screenshot_20220903_202119](https://user-images.githubusercontent.com/25227022/188285139-93761c58-7cd2-4939-94c2-dc8d8a2e3bd8.png)|

2022-09-03 19:28 UTC, Ismailco commented on index.html
> +      </ul>
- [ ] Your social links icons are not displayed correctly kindly consider fixing this so your icons are displayed on the page correctly this will improve the User Experience on your site

![](https://user-images.githubusercontent.com/58642949/188280697-b243a6ea-b479-4672-87f0-c50ab639756d.png)

2022-09-03 19:28 UTC, Ismailco commented on index.html
> +<body>
- [ ] Your page is aligned to the left with big with space on the right, kindly make sure to center the page so it looks like the Figma design

![Screenshot_20220903_202650](https://user-images.githubusercontent.com/25227022/188285256-0f45287c-3294-4793-b1aa-f1ad2a55000e.png)

2022-09-04 05:06 UTC, emmiiorji approved these changes
Hi @rehanullah748, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congratulations](https://user-images.githubusercontent.com/20554583/188298634-cadae473-8391-48ef-b7de-96cb3ddab4d6.gif)


## Good Highlights ✔

- Good commit messages
- Linter checks are passing
- Adherence to GitHub flow


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-04 14:32 UTC, merged